Customize theme, fix twitter URL, flesh out about page
rcos/rcos.github.io pull request #1
Opened 2018-05-16 16:01 UTC by kburk1997

2018-05-16 19:49 UTC, aeksco commented
:+1: Nice work!

2018-05-17 15:17 UTC, agundy requested changes
fix a typo and a better link

2018-05-17 15:17 UTC, agundy commented on about.md
> +Our projects can be found on our open source project managent platform, [Observatory](http://rcos.io).
managent -> management

2018-05-17 15:17 UTC, agundy commented on about.md
> +Our projects can be found on our open source project managent platform, [Observatory](http://rcos.io).
and https://rcos.io/ is better than http

2018-05-17 15:17 UTC, agundy commented on _includes/footer.html
> +    <p class="small">© Copyright {{ site.time | date: '%Y' }} {{ site.author }} | <a href="https://github.com/rcos/rcos.github.io">Github</a></p>
might be good to also link to rcos.io since it's the main place to see what rcos is up to

2018-05-17 18:02 UTC, kburk1997 commented on about.md
> +Our projects can be found on our open source project managent platform, [Observatory](http://rcos.io).
Whoops -- didn't catch that lol

2018-05-17 18:25 UTC, kburk1997 commented
Fixed that typo and that link, works on my local machine

2018-05-24 17:54 UTC, agundy approved these changes

2018-05-25 05:04 UTC, merged